# Generated by Django 5.2.14 on 2026-05-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='clases',
        ),
    ]
