# Generated by Django 5.2.14 on 2026-05-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transections', '0003_remove_borrow_status_borrow_fine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(),
        ),
    ]
