# Generated by Django 5.2.14 on 2026-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transections', '0007_alter_borrow_borrow_date_alter_borrow_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(),
        ),
    ]
