# Generated by Django 5.2.14 on 2026-05-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('isbn', models.CharField()),
                ('descriptions', models.TextField()),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
                ('published_date', models.DateField()),
                ('created_at', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='category.category')),
            ],
        ),
    ]
