# Generated by Django 5.2.14 on 2026-05-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
